name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: sudo apt install xorg-dev libxcb-composite0-dev
    - name: Build
      run: cargo build --verbose --release
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: myip
        path: target/release/myip
